require('es6-shim');

var radmin = {
  Breadcrumb: require('./breadcrumb'),
  BreadcrumbBar: require('./breadcrumbBar'),
  Calendar: require('./calendar'),
  CheckBox: require('./checkBox'),
  ClipBoard: require('./clipboard'),
  CheckBoxGroup: require('./checkBoxGroup'),
  DatePicker: require('./datePicker'),
  DateRangePicker: require('./dateRangePicker'),
  Dropdown: require('./dropdown'),
  DropDownMenu: require('./dropDownMenu'),
  Form: require('./form'),
  Input: require('./input'),
  Image: require('./image'),
  ImageCreator: require('./imageCreator'),
  InlineEdit: require('./inlineEdit'),
  ListMenu: require('./listMenu'),
  Loading: require('./loading'),
  LoadingCss: require('./loadingCss'),
  LinkageSelect:require('./linkageSelect'),
  Navigator: require('./navigator'),
  NewTabs: require('./newTabs'),
  Popover: require('./popover'),
  Popup: require('./popup'),
  Prompt: require('./prompt'),
  Radio: require('./radio'),
  RadioGroup: require('./radioGroup'),
  SearchBar: require('./searchBar'),
  Select: require('./select'),
  Slider: require('./slider'),
  SlidePanel: require('./slidePanel'),
  Spin: require('./spin'),
  Swiper: require('./swiper'),
  Switch: require('./switch'),
  Table: require('./table'),
  Tabs: require('./tabs'),
  Tags: require('./tags'),
  Time: require('./time'),
  ToolTip: require('./toolTip'),
  TreeSelect: require('./treeSelect'),
  Utils: require('./utils')
};

module.exports = radmin;
